/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'compensation' : IDL.Text,
  'descriptionUrl' : IDL.Text,
  'jobTitle' : IDL.Text,
  'contactEmail' : IDL.Text,
  'location' : IDL.Text,
});
export const ContentSection = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'labelText' : IDL.Text,
});
export const Profile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminJobListingWithDescription' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [JobListing, ContentSection],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [JobListing], ['query']),
  'getJobListingWithDescription' : IDL.Func(
      [IDL.Nat],
      [JobListing, ContentSection],
      ['query'],
    ),
  'getJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getJobListingsWithDescription' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(JobListing, ContentSection))],
      ['query'],
    ),
  'getJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getListingWithDividedDescription' : IDL.Func(
      [IDL.Nat],
      [JobListing, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveContactForm' : IDL.Func([ContactForm], [], []),
  'saveProfile' : IDL.Func([Profile], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'compensation' : IDL.Text,
    'descriptionUrl' : IDL.Text,
    'jobTitle' : IDL.Text,
    'contactEmail' : IDL.Text,
    'location' : IDL.Text,
  });
  const ContentSection = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'labelText' : IDL.Text,
  });
  const Profile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminJobListingWithDescription' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [JobListing, ContentSection],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [JobListing], ['query']),
    'getJobListingWithDescription' : IDL.Func(
        [IDL.Nat],
        [JobListing, ContentSection],
        ['query'],
      ),
    'getJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getJobListingsWithDescription' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(JobListing, ContentSection))],
        ['query'],
      ),
    'getJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getListingWithDividedDescription' : IDL.Func(
        [IDL.Nat],
        [JobListing, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveContactForm' : IDL.Func([ContactForm], [], []),
    'saveProfile' : IDL.Func([Profile], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };